import { SymbolSet } from "./symbol-set.js";

export const weather = new SymbolSet([
  `ac_unit`,
  `severe_cold`,
  `mode_dual`,
  `storm`,
  `cyclone`,
  `flood`,
  `air `,
  `landslide`,
  `airwave`,
  `heat `,
  `rainy_heavy`,
  `mist `,
  `tornado `,
  `rainy_light `,
  `tsunami `,
  `rainy_snow `,
  `water `,
  `nights_stay `,
  `foggy `,
  `thunderstorm `,
  `weather_hail `,
  `weather_mix `,
  `weather_snowy `,
  `cloudy_snowing `,
  `routine `,
  `partly_cloudy_day `,
  `rainy `,
  `clear_day `,
  `sunny `,
  `sunny_snowing `,
  `snowing_heavy `,
  `clear_night `,
  `cloud `,
]);