import { SymbolSet } from "./symbol-set.js";

export const weather = new SymbolSet("weather", [
  { name: "storm", luminance: 0 },
  { name: "tornado", luminance: 14 },
  { name: "cyclone", luminance: 41 },
  { name: "ac_unit", luminance: 55 },
  { name: "tsunami", luminance: 68 },
  { name: "landslide", luminance: 77 },
  { name: "mode_dual", luminance: 87 },
  { name: "nights_stay", luminance: 96 },
  { name: "clear_night", luminance: 96 },
  { name: "airwave", luminance: 105 },
  { name: "routine", luminance: 105 },
  { name: "severe_cold", luminance: 109 },
  { name: "flood", luminance: 114 },
  { name: "rainy_heavy", luminance: 114 },
  { name: "rainy_light", luminance: 118 },
  { name: "clear_day", luminance: 123 },
  { name: "sunny", luminance: 123 },
  { name: "weather_snowy", luminance: 128 },
  { name: "partly_cloudy_day", luminance: 128 },
  { name: "mist", luminance: 137 },
  { name: "foggy", luminance: 141 },
  { name: "thunderstorm", luminance: 141 },
  { name: "weather_hail", luminance: 141 },
  { name: "weather_mix", luminance: 141 },
  { name: "cloudy_snowing", luminance: 141 },
  { name: "rainy", luminance: 141 },
  { name: "air", luminance: 146 },
  { name: "rainy_snow", luminance: 150 },
  { name: "water", luminance: 159 },
  { name: "heat", luminance: 168 },
  { name: "cloud", luminance: 168 },
  { name: "sunny_snowing", luminance: 178 },
  { name: "snowing_heavy", luminance: 255 },
]);
