import { SymbolSet } from "./symbol-set.js";

export const weather = new SymbolSet(
  "weather",
  "Weather",
  [
  { name: "landslide", luminance: 0, filled: "false" },
  { name: "flood", luminance: 48, filled: "false" },
  { name: "cyclone", luminance: 54, filled: "false" },
  { name: "tsunami", luminance: 57, filled: "false" },
  { name: "ac_unit", luminance: 61, filled: "false" },
  { name: "storm", luminance: 70, filled: "false" },
  { name: "mode_dual", luminance: 92, filled: "false" },
  { name: "severe_cold", luminance: 96, filled: "false" },
  { name: "foggy", luminance: 102, filled: "false" },
  { name: "partly_cloudy_day", luminance: 102, filled: "false" },
  { name: "routine", luminance: 108, filled: "false" },
  { name: "air", luminance: 118, filled: "false" },
  { name: "thunderstorm", luminance: 121, filled: "false" },
  { name: "tornado", luminance: 128, filled: "false" },
  { name: "rainy", luminance: 128, filled: "false" },
  { name: "clear_day", luminance: 128, filled: "false" },
  { name: "sunny", luminance: 128, filled: "false" },
  { name: "weather_snowy", luminance: 131, filled: "false" },
  { name: "airwave", luminance: 150, filled: "false" },
  { name: "water", luminance: 150, filled: "false" },
  { name: "cloudy_snowing", luminance: 150, filled: "false" },
  { name: "mist", luminance: 156, filled: "false" },
  { name: "nights_stay", luminance: 156, filled: "false" },
  { name: "weather_mix", luminance: 163, filled: "false" },
  { name: "weather_hail", luminance: 166, filled: "false" },
  { name: "sunny_snowing", luminance: 182, filled: "false" },
  { name: "clear_night", luminance: 185, filled: "false" },
  { name: "rainy_heavy", luminance: 194, filled: "false" },
  { name: "cloud", luminance: 194, filled: "false" },
  { name: "rainy_light", luminance: 207, filled: "false" },
  { name: "rainy_snow", luminance: 214, filled: "false" },
  { name: "heat", luminance: 220, filled: "false" },
  { name: "snowing_heavy", luminance: 255, filled: "false" }
]);
