module.exports = {
  id: "weather",
  name: "Weather",
  symbols: [
    { name: "ac_unit", filled: false }, 
    { name: "severe_cold", filled: false }, 
    { name: "mode_dual", filled: false }, 
    { name: "storm", filled: false }, 
    { name: "cyclone", filled: false }, 
    { name: "flood", filled: false }, 
    { name: "air", filled: false }, 
    { name: "landslide", filled: false }, 
    { name: "airwave", filled: false }, 
    { name: "heat", filled: false }, 
    { name: "rainy_heavy", filled: false }, 
    { name: "mist", filled: false }, 
    { name: "tornado", filled: false }, 
    { name: "rainy_light", filled: false }, 
    { name: "tsunami", filled: false }, 
    { name: "rainy_snow", filled: false }, 
    { name: "water", filled: false }, 
    { name: "nights_stay", filled: false }, 
    { name: "foggy", filled: false }, 
    { name: "thunderstorm", filled: false }, 
    { name: "weather_hail", filled: false }, 
    { name: "weather_mix", filled: false }, 
    { name: "weather_snowy", filled: false }, 
    { name: "cloudy_snowing", filled: false }, 
    { name: "routine", filled: false }, 
    { name: "partly_cloudy_day", filled: false }, 
    { name: "rainy", filled: false }, 
    { name: "clear_day", filled: false }, 
    { name: "sunny", filled: false }, 
    { name: "sunny_snowing", filled: false }, 
    { name: "snowing_heavy", filled: false }, 
    { name: "clear_night", filled: false }, 
    { name: "cloud", filled: false }, 
  ],
};