module.exports = {
  id: "physical-network",
  name: "Physical Network",
  symbols: [
    { name: "360 ", filled: false },
    { name: "360 ", filled: true },
    { name: "add home", filled: false },
    { name: "add home", filled: true },
    { name: "add home work", filled: false },
    { name: "add home work", filled: true },
    { name: "add location", filled: false },
    { name: "add location", filled: true },
    { name: "add location alt", filled: false },
    { name: "add location alt", filled: true },
    { name: "add road", filled: false },
    { name: "add road", filled: true },
    { name: "airline stops", filled: false },
    { name: "airline stops", filled: true },
    { name: "alt route", filled: false },
    { name: "alt route", filled: true },
    { name: "beenhere", filled: false },
    { name: "beenhere", filled: true },
    { name: "business center", filled: false },
    { name: "business center", filled: true },
    { name: "castle", filled: false },
    { name: "castle", filled: true },
    { name: "church", filled: false },
    { name: "church", filled: true },
    { name: "cleaning services", filled: false },
    { name: "cleaning services", filled: true },
    { name: "compass calibration", filled: false },
    { name: "compass calibration", filled: true },
    { name: "connecting airports", filled: false },
    { name: "connecting airports", filled: true },
    { name: "crisis alert", filled: false },
    { name: "crisis alert", filled: true },
    { name: "directions", filled: false },
    { name: "directions", filled: true },
    { name: "directions alt", filled: false },
    { name: "directions alt", filled: true },
    { name: "directions alt off", filled: false },
    { name: "directions alt off", filled: true },
    { name: "directions off", filled: false },
    { name: "directions off", filled: true },
    { name: "east", filled: false },
    { name: "east", filled: true },
    { name: "edit attributes", filled: false },
    { name: "edit attributes", filled: true },
    { name: "edit location", filled: false },
    { name: "edit location", filled: true },
    { name: "edit location alt", filled: false },
    { name: "edit location alt", filled: true },
    { name: "edit road", filled: false },
    { name: "edit road", filled: true },
    { name: "emergency", filled: false },
    { name: "emergency", filled: true },
    { name: "EV station", filled: false },
    { name: "EV station", filled: true },
    { name: "Explore", filled: false },
    { name: "Explore", filled: true },
    { name: "Explore nearby", filled: false },
    { name: "Explore nearby", filled: true },
    { name: "explore off", filled: false },
    { name: "explore off", filled: true },
    { name: "factory", filled: false },
    { name: "factory", filled: true },
    { name: "file map", filled: false },
    { name: "file map", filled: true },
    { name: "fire hydrant", filled: false },
    { name: "fire hydrant", filled: true },
    { name: "fire truck", filled: false },
    { name: "fire truck", filled: true },
    { name: "flag", filled: false },
    { name: "flag", filled: true },
    { name: "flag circle", filled: false },
    { name: "flag circle", filled: true },
    { name: "flight class", filled: false },
    { name: "flight class", filled: true },
    { name: "fmd bad", filled: false },
    { name: "fmd bad", filled: true },
    { name: "fort", filled: false },
    { name: "fort", filled: true },
    { name: "handyman", filled: false },
    { name: "handyman", filled: true },
    { name: "home pin", filled: false },
    { name: "home pin", filled: true },
    { name: "home repair service", filled: false },
    { name: "home repair service", filled: true },
    { name: "home work", filled: false },
    { name: "home work", filled: true },
    { name: "local activity", filled: false },
    { name: "local activity", filled: true },
    { name: "local atm", filled: false },
    { name: "local atm", filled: true },
    { name: "local car wash", filled: false },
    { name: "local car wash", filled: true },
    { name: "local gas station", filled: false },
    { name: "local gas station", filled: true },
    { name: "local parking", filled: false },
    { name: "local parking", filled: true },
    { name: "local pizza", filled: false },
    { name: "local pizza", filled: true },
    { name: "local post office", filled: false },
    { name: "local post office", filled: true },
    { name: "location away", filled: false },
    { name: "location away", filled: true },
    { name: "location on", filled: false },
    { name: "location on", filled: true },
    { name: "map", filled: false },
    { name: "map", filled: true },
    { name: "minor crash", filled: false },
    { name: "minor crash", filled: true },
    { name: "mode of travel", filled: false },
    { name: "mode of travel", filled: true },
    { name: "move", filled: false },
    { name: "move", filled: true },
    { name: "move location", filled: false },
    { name: "move location", filled: true },
    { name: "moved location", filled: false },
    { name: "moved location", filled: true },
    { name: "moving", filled: false },
    { name: "moving", filled: true },
    { name: "moving ministry", filled: false },
    { name: "moving ministry", filled: true },
    { name: "multiple stop", filled: false },
    { name: "multiple stop", filled: true },
    { name: "my location", filled: false },
    { name: "my location", filled: true },
    { name: "navigation", filled: false },
    { name: "navigation", filled: true },
    { name: "near me", filled: false },
    { name: "near me", filled: true },
    { name: "near me disabled", filled: false },
    { name: "near me disabled", filled: true },
    { name: "north", filled: false },
    { name: "north", filled: true },
    { name: "north east", filled: false },
    { name: "north east", filled: true },
    { name: "north west", filled: false },
    { name: "north west", filled: true },
    { name: "not listed location", filled: false },
    { name: "not listed location", filled: true },
    { name: "package", filled: false },
    { name: "package", filled: true },
    { name: "package 2", filled: false },
    { name: "package 2", filled: true },
    { name: "person pin", filled: false },
    { name: "person pin", filled: true },
    { name: "person pin circle", filled: false },
    { name: "person pin circle", filled: true },
    { name: "pest control rodent", filled: false },
    { name: "pest control rodent", filled: true },
    { name: "pest control", filled: false },
    { name: "pest control", filled: true },
    { name: "pin drop", filled: false },
    { name: "pin drop", filled: true },
    { name: "plumbing", filled: false },
    { name: "plumbing", filled: true },
    { name: "remove road", filled: false },
    { name: "remove road", filled: true },
    { name: "run circle", filled: false },
    { name: "run circle", filled: true },
    { name: "safety check ", filled: false },
    { name: "safety check ", filled: true },
    { name: "safety check off", filled: false },
    { name: "safety check off", filled: true },
    { name: "satellite", filled: false },
    { name: "satellite", filled: true },
    { name: "share location", filled: false },
    { name: "share location", filled: true },
    { name: "signpost", filled: false },
    { name: "signpost", filled: true },
    { name: "sos", filled: false },
    { name: "sos", filled: true },
    { name: "south", filled: false },
    { name: "south", filled: true },
    { name: "south east", filled: false },
    { name: "south east", filled: true },
    { name: "south west", filled: false },
    { name: "south west", filled: true },
    { name: "stadium", filled: false },
    { name: "stadium", filled: true },
    { name: "streetview", filled: false },
    { name: "streetview", filled: true },
    { name: "synagogue", filled: false },
    { name: "synagogue", filled: true },
    { name: "things to do", filled: false },
    { name: "things to do", filled: true },
    { name: "tour", filled: false },
    { name: "tour", filled: true },
    { name: "traffic", filled: false },
    { name: "traffic", filled: true },
    { name: "transit enterexit", filled: false },
    { name: "transit enterexit", filled: true },
    { name: "trip origin", filled: false },
    { name: "trip origin", filled: true },
    { name: "universal local", filled: false },
    { name: "universal local", filled: true },
    { name: "warehouse", filled: false },
    { name: "warehouse", filled: true },
    { name: "west", filled: false },
    { name: "west", filled: true },
    { name: "where to vote", filled: false },
    { name: "where to vote", filled: true },
    { name: "wrong location", filled: false },
    { name: "wrong location", filled: true },
    { name: "zoom in map", filled: false },
    { name: "zoom in map", filled: true },
    { name: "zoom out map", filled: false },
    { name: "zoom out map", filled: true },
    { name: "agriculture", filled: false },
    { name: "agriculture", filled: true },
    { name: "airlines", filled: false },
    { name: "airlines", filled: true },
    { name: "airport shuttle", filled: false },
    { name: "airport shuttle", filled: true },
    { name: "ambulance", filled: false },
    { name: "ambulance", filled: true },
    { name: "auto towing", filled: false },
    { name: "auto towing", filled: true },
    { name: "auto transmission", filled: false },
    { name: "auto transmission", filled: true },
    { name: "bike scooter", filled: false },
    { name: "bike scooter", filled: true },
    { name: "bus alert", filled: false },
    { name: "bus alert", filled: true },
    { name: "car crash", filled: false },
    { name: "car crash", filled: true },
    { name: "car tag", filled: false },
    { name: "car tag", filled: true },
    { name: "commute", filled: false },
    { name: "commute", filled: true },
    { name: "departure board", filled: false },
    { name: "departure board", filled: true },
    { name: "directions boat", filled: false },
    { name: "directions boat", filled: true },
    { name: "directions bus", filled: false },
    { name: "directions bus", filled: true },
    { name: "directions car", filled: false },
    { name: "directions car", filled: true },
    { name: "directions railway", filled: false },
    { name: "directions railway", filled: true },
    { name: "directions subway", filled: false },
    { name: "directions subway", filled: true },
    { name: "electric bike", filled: false },
    { name: "electric bike", filled: true },
    { name: "electric car", filled: false },
    { name: "electric car", filled: true },
    { name: "electric moped", filled: false },
    { name: "electric moped", filled: true },
    { name: "electric rickshaw", filled: false },
    { name: "electric rickshaw", filled: true },
    { name: "electric scooter", filled: false },
    { name: "electric scooter", filled: true },
    { name: "flight", filled: false },
    { name: "flight", filled: true },
    { name: "flight land", filled: false },
    { name: "flight land", filled: true },
    { name: "flight takeoff", filled: false },
    { name: "flight takeoff", filled: true },
    { name: "flightsmode", filled: false },
    { name: "flightsmode", filled: true },
    { name: "fork left", filled: false },
    { name: "fork left", filled: true },
    { name: "fork right", filled: false },
    { name: "fork right", filled: true },
    { name: "local shipping", filled: false },
    { name: "local shipping", filled: true },
    { name: "local taxi", filled: false },
    { name: "local taxi", filled: true },
    { name: "motorcycle", filled: false },
    { name: "motorcycle", filled: true },
    { name: "no crash", filled: false },
    { name: "no crash", filled: true },
    { name: "no transfer", filled: false },
    { name: "no transfer", filled: true },
    { name: "pedal bike", filled: false },
    { name: "pedal bike", filled: true },
    { name: "railway alert", filled: false },
    { name: "railway alert", filled: true },
    { name: "rv hookup", filled: false },
    { name: "rv hookup", filled: true },
    { name: "sailing", filled: false },
    { name: "sailing", filled: true },
    { name: "snowmobile", filled: false },
    { name: "snowmobile", filled: true },
    { name: "subway", filled: false },
    { name: "subway", filled: true },
    { name: "swap driving apps", filled: false },
    { name: "swap driving apps", filled: true },
    { name: "swap driving apps wheel", filled: false },
    { name: "swap driving apps wheel", filled: true },
    { name: "taxi alert", filled: false },
    { name: "taxi alert", filled: true },
    { name: "tire repair", filled: false },
    { name: "tire repair", filled: true },
    { name: "train", filled: false },
    { name: "train", filled: true },
    { name: "tram", filled: false },
    { name: "tram", filled: true },
    { name: "transportation", filled: false },
    { name: "transportation", filled: true },
    { name: "turn left", filled: false },
    { name: "turn left", filled: true },
    { name: "turn right", filled: false },
    { name: "turn right", filled: true },
    { name: "turn sharp left", filled: false },
    { name: "turn sharp left", filled: true },
    { name: "turn sharp right", filled: false },
    { name: "turn sharp right", filled: true },
    { name: "turn slight left", filled: false },
    { name: "turn slight left", filled: true },
    { name: "turn slight right", filled: false },
    { name: "turn slight right", filled: true },
    { name: "two wheeler", filled: false },
    { name: "two wheeler", filled: true },
    { name: "u turn left", filled: false },
    { name: "u turn left", filled: true },
    { name: "u turn right", filled: false },
    { name: "u turn right", filled: true },
    { name: "airplane ticket", filled: false },
    { name: "airplane ticket", filled: true },
    { name: "apartment", filled: false },
    { name: "apartment", filled: true },
    { name: "car rental", filled: false },
    { name: "car rental", filled: true },
    { name: "car repair", filled: false },
    { name: "car repair", filled: true },
    { name: "carry on bag", filled: false },
    { name: "carry on bag", filled: true },
    { name: "child friendly", filled: false },
    { name: "child friendly", filled: true },
    { name: "checked bag", filled: false },
    { name: "checked bag", filled: true },
    { name: "escalator", filled: false },
    { name: "escalator", filled: true },
    { name: "flights and hotels", filled: false },
    { name: "flights and hotels", filled: true },
    { name: "location city", filled: false },
    { name: "location city", filled: true },
    { name: "stairs", filled: false },
    { name: "stairs", filled: true },
    { name: "toys", filled: false },
    { name: "toys", filled: true },
    { name: "inventory 2", filled: false },
    { name: "inventory 2", filled: true },
    { name: "box", filled: false },
    { name: "box", filled: true },
    { name: "box add", filled: false },
    { name: "box add", filled: true },
    { name: "box edit", filled: false },
    { name: "box edit", filled: true },
    { name: "forklift", filled: false },
    { name: "forklift", filled: true },
    { name: "front loader", filled: false },
    { name: "front loader", filled: true },
    { name: "loyalty", filled: false },
    { name: "loyalty", filled: true },
    { name: "trolley", filled: false },
    { name: "trolley", filled: true },
    { name: "anchor", filled: false },
    { name: "anchor", filled: true },
    { name: "manufacturing", filled: false },
    { name: "manufacturing", filled: true },
    { name: "manage history", filled: false },
    { name: "manage history", filled: true },
    { name: "ramp left", filled: false },
    { name: "ramp left", filled: true },
    { name: "ramp right", filled: false },
    { name: "ramp right", filled: true },
    { name: "roundabout left", filled: false },
    { name: "roundabout left", filled: true },
    { name: "roundabout right", filled: false },
    { name: "roundabout right", filled: true },
    { name: "shopping cart checkout", filled: false },
    { name: "shopping cart checkout", filled: true },
    { name: "settings", filled: false },
    { name: "settings", filled: true },
    { name: "token", filled: false },
    { name: "token", filled: true },
    { name: "delete sweep", filled: false },
    { name: "delete sweep", filled: true },
    { name: "repartition", filled: false },
    { name: "repartition", filled: true },
    { name: "cycle", filled: false },
    { name: "cycle", filled: true },
    { name: "arrow or edge", filled: false },
    { name: "arrow or edge", filled: true },
    { name: "deployed code history", filled: false },
    { name: "deployed code history", filled: true },
    { name: "precision manufacturing", filled: false },
    { name: "precision manufacturing", filled: true },
    { name: "shopping basket", filled: false },
    { name: "shopping basket", filled: true },
    { name: "garage home", filled: false },
    { name: "garage home", filled: true },
    { name: "garage", filled: false },
    { name: "garage", filled: true },
    { name: "valve", filled: false },
    { name: "valve", filled: true },
    { name: "sprinkler", filled: false },
    { name: "sprinkler", filled: true },
  ],
};
