module.exports = {
  id: "telecom-network",
  name: "Telecom Network",
  symbols: [
    { name: "electrical services", filled: true },
    { name: "electrical services", filled: false },
    { name: "call", filled: true },
    { name: "call", filled: false },
    { name: "call end", filled: true },
    { name: "call end", filled: false },
    { name: "call log", filled: true },
    { name: "call log", filled: false },
    { name: "call made", filled: true },
    { name: "call made", filled: false },
    { name: "call merge", filled: true },
    { name: "call merge", filled: false },
    { name: "call missed", filled: true },
    { name: "call missed", filled: false },
    { name: "call missed outgoing", filled: true },
    { name: "call missed outgoing", filled: false },
    { name: "call quality", filled: true },
    { name: "call quality", filled: false },
    { name: "call received", filled: true },
    { name: "call received", filled: false },
    { name: "call split", filled: true },
    { name: "call split", filled: false },
    { name: "cancel schedule send", filled: true },
    { name: "cancel schedule send", filled: false },
    { name: "cell tower", filled: true },
    { name: "cell tower", filled: false },
    { name: "cell wifi", filled: true },
    { name: "cell wifi", filled: false },
    { name: "chat", filled: true },
    { name: "chat", filled: false },
    { name: "chat bubble", filled: true },
    { name: "chat bubble", filled: false },
    { name: "chat error", filled: true },
    { name: "chat error", filled: false },
    { name: "comment", filled: true },
    { name: "comment", filled: false },
    { name: "contact mail", filled: true },
    { name: "contact mail", filled: false },
    { name: "contact phone", filled: true },
    { name: "contact phone", filled: false },
    { name: "contact support", filled: true },
    { name: "contact support", filled: false },
    { name: "contacts", filled: true },
    { name: "contacts", filled: false },
    { name: "dialer sip", filled: true },
    { name: "dialer sip", filled: false },
    { name: "dialpad", filled: true },
    { name: "dialpad", filled: false },
    { name: "e911 avatar", filled: true },
    { name: "e911 avatar", filled: false },
    { name: "forum", filled: true },
    { name: "forum", filled: false },
    { name: "forward to inbox", filled: true },
    { name: "forward to inbox", filled: false },
    { name: "hub", filled: true },
    { name: "hub", filled: false },
    { name: "hourglass bottom", filled: true },
    { name: "hourglass bottom", filled: false },
    { name: "hourglass top", filled: true },
    { name: "hourglass top", filled: false },
    { name: "hub", filled: true },
    { name: "hub", filled: false },
    { name: "inbox", filled: true },
    { name: "inbox", filled: false },
    { name: "inbox customize", filled: true },
    { name: "inbox customize", filled: false },
    { name: "lan", filled: true },
    { name: "lan", filled: false },
    { name: "link", filled: true },
    { name: "link", filled: false },
    { name: "link off", filled: true },
    { name: "link off", filled: false },
    { name: "live help", filled: true },
    { name: "live help", filled: false },
    { name: "mail", filled: true },
    { name: "mail", filled: false },
    { name: "mark as unread", filled: true },
    { name: "mark as unread", filled: false },
    { name: "mark chat unread", filled: true },
    { name: "mark chat unread", filled: false },
    { name: "mark email read", filled: true },
    { name: "mark email read", filled: false },
    { name: "mark unread chat alt", filled: true },
    { name: "mark unread chat alt", filled: false },
    { name: "markunread mailbox", filled: true },
    { name: "markunread mailbox", filled: false },
    { name: "move to inbox", filled: true },
    { name: "move to inbox", filled: false },
    { name: "nat", filled: true },
    { name: "nat", filled: false },
    { name: "network intelligence update", filled: true },
    { name: "network intelligence update", filled: false },
    { name: "network manage", filled: true },
    { name: "network manage", filled: false },
    { name: "next plan", filled: true },
    { name: "next plan", filled: false },
    { name: "notification multiple", filled: true },
    { name: "notification multiple", filled: false },
    { name: "notifications active", filled: true },
    { name: "notifications active", filled: false },
    { name: "notifications off", filled: true },
    { name: "notifications off", filled: false },
    { name: "notifications unread", filled: true },
    { name: "notifications unread", filled: false },
    { name: "outbox", filled: true },
    { name: "outbox", filled: false },
    { name: "perm phone msg", filled: true },
    { name: "perm phone msg", filled: false },
    { name: "person search", filled: true },
    { name: "person search", filled: false },
    { name: "phone bluetooth speaker", filled: true },
    { name: "phone bluetooth speaker", filled: false },
    { name: "phone callback", filled: true },
    { name: "phone callback", filled: false },
    { name: "phone disabled", filled: true },
    { name: "phone disabled", filled: false },
    { name: "phone enabled", filled: true },
    { name: "phone enabled", filled: false },
    { name: "phone forwarded", filled: true },
    { name: "phone forwarded", filled: false },
    { name: "phone in talk", filled: true },
    { name: "phone in talk", filled: false },
    { name: "phone locked", filled: true },
    { name: "phone locked", filled: false },
    { name: "phone missed", filled: true },
    { name: "phone missed", filled: false },
    { name: "phone paused", filled: true },
    { name: "phone paused", filled: false },
    { name: "phonelink erase", filled: true },
    { name: "phonelink erase", filled: false },
    { name: "phonelink lock", filled: true },
    { name: "phonelink lock", filled: false },
    { name: "phonelink ring", filled: true },
    { name: "phonelink ring", filled: false },
    { name: "play for work", filled: true },
    { name: "play for work", filled: false },
    { name: "power settings new", filled: true },
    { name: "power settings new", filled: false },
    { name: "present to all", filled: true },
    { name: "present to all", filled: false },
    { name: "quickreply", filled: true },
    { name: "quickreply", filled: false },
    { name: "reviews", filled: true },
    { name: "reviews", filled: false },
    { name: "ring volume", filled: true },
    { name: "ring volume", filled: false },
    { name: "rtt", filled: true },
    { name: "rtt", filled: false },
    { name: "satellite alt", filled: true },
    { name: "satellite alt", filled: false },
    { name: "schedule send", filled: true },
    { name: "schedule send", filled: false },
    { name: "score", filled: true },
    { name: "score", filled: false },
    { name: "send", filled: true },
    { name: "send", filled: false },
    { name: "send and archive", filled: true },
    { name: "send and archive", filled: false },
    { name: "settings bluetooth", filled: true },
    { name: "settings bluetooth", filled: false },
    { name: "settings phone", filled: true },
    { name: "settings phone", filled: false },
    { name: "signal cellular add", filled: true },
    { name: "signal cellular add", filled: false },
    { name: "sip", filled: true },
    { name: "sip", filled: false },
    { name: "sms", filled: true },
    { name: "sms", filled: false },
    { name: "speaker notes", filled: true },
    { name: "speaker notes", filled: false },
    { name: "speaker notes off", filled: true },
    { name: "speaker notes off", filled: false },
    { name: "speaker phone", filled: true },
    { name: "speaker phone", filled: false },
    { name: "spoke", filled: true },
    { name: "spoke", filled: false },
    { name: "stacked email", filled: true },
    { name: "stacked email", filled: false },
    { name: "stacked inbox", filled: true },
    { name: "stacked inbox", filled: false },
    { name: "swap calls", filled: true },
    { name: "swap calls", filled: false },
    { name: "thread unread", filled: true },
    { name: "thread unread", filled: false },
    { name: "tooltip", filled: true },
    { name: "tooltip", filled: false },
    { name: "topic", filled: true },
    { name: "topic", filled: false },
    { name: "unarchive", filled: true },
    { name: "unarchive", filled: false },
    { name: "unsubscribe", filled: true },
    { name: "unsubscribe", filled: false },
    { name: "upcoming", filled: true },
    { name: "upcoming", filled: false },
    { name: "video chat", filled: true },
    { name: "video chat", filled: false },
    { name: "voice chat", filled: true },
    { name: "voice chat", filled: false },
    { name: "voicemail", filled: true },
    { name: "voicemail", filled: false },
    { name: "wifi add", filled: true },
    { name: "wifi add", filled: false },
    { name: "wifi calling", filled: true },
    { name: "wifi calling", filled: false },
    { name: "wifi channel", filled: true },
    { name: "wifi channel", filled: false },
    { name: "wifi proxy", filled: true },
    { name: "wifi proxy", filled: false },
    { name: "account tree", filled: true },
    { name: "account tree", filled: false },
    { name: "area chart", filled: true },
    { name: "area chart", filled: false },
    { name: "analytics", filled: true },
    { name: "analytics", filled: false },
    { name: "barcode scanner", filled: true },
    { name: "barcode scanner", filled: false },
    { name: "bubble chart", filled: true },
    { name: "bubble chart", filled: false },
    { name: "candlestick chart", filled: true },
    { name: "candlestick chart", filled: false },
    { name: "chart data", filled: true },
    { name: "chart data", filled: false },
    { name: "conversion path", filled: true },
    { name: "conversion path", filled: false },
    { name: "conversion path off", filled: true },
    { name: "conversion path off", filled: false },
    { name: "currency exchange", filled: true },
    { name: "currency exchange", filled: false },
    { name: "data exploration", filled: true },
    { name: "data exploration", filled: false },
    { name: "family history", filled: true },
    { name: "family history", filled: false },
    { name: "finance mode", filled: true },
    { name: "finance mode", filled: false },
    { name: "flowsheet", filled: true },
    { name: "flowsheet", filled: false },
    { name: "mediation", filled: true },
    { name: "mediation", filled: false },
    { name: "mitre", filled: true },
    { name: "mitre", filled: false },
    { name: "network node", filled: true },
    { name: "network node", filled: false },
    { name: "receipt long", filled: true },
    { name: "receipt long", filled: false },
    { name: "schema", filled: true },
    { name: "schema", filled: false },
    { name: "scatter plot", filled: true },
    { name: "scatter plot", filled: false },
    { name: "send money", filled: true },
    { name: "send money", filled: false },
    { name: "tenancy", filled: true },
    { name: "tenancy", filled: false },
    { name: "track changes", filled: true },
    { name: "track changes", filled: false },
    { name: "timeline", filled: true },
    { name: "timeline", filled: false },
    { name: "ssid chart", filled: true },
    { name: "ssid chart", filled: false },
    { name: "trending down", filled: true },
    { name: "trending down", filled: false },
    { name: "trending up", filled: true },
    { name: "trending up", filled: false },
    { name: "1x mobiledata badge", filled: true },
    { name: "1x mobiledata badge", filled: false },
    { name: "3g mobiledata badge", filled: true },
    { name: "3g mobiledata badge", filled: false },
    { name: "4g mobiledata badge", filled: true },
    { name: "4g mobiledata badge", filled: false },
    { name: "battery change", filled: true },
    { name: "battery change", filled: false },
    { name: "bigtop updates", filled: true },
    { name: "bigtop updates", filled: false },
    { name: "bluetooth", filled: true },
    { name: "bluetooth", filled: false },
    { name: "bluetooth connected", filled: true },
    { name: "bluetooth connected", filled: false },
    { name: "bluetooth drive", filled: true },
    { name: "bluetooth drive", filled: false },
    { name: "bluetooth searching", filled: true },
    { name: "bluetooth searching", filled: false },
    { name: "cable", filled: true },
    { name: "cable", filled: false },
    { name: "charger", filled: true },
    { name: "charger", filled: false },
    { name: "network check", filled: true },
    { name: "network check", filled: false },
    { name: "network locked", filled: true },
    { name: "network locked", filled: false },
    { name: "network wifi locked", filled: true },
    { name: "network wifi locked", filled: false },
    { name: "nfc", filled: true },
    { name: "nfc", filled: false },
    { name: "password", filled: true },
    { name: "password", filled: false },
    { name: "settings system daydream", filled: true },
    { name: "settings system daydream", filled: false },
    { name: "radar", filled: true },
    { name: "radar", filled: false },
    { name: "rss feed", filled: true },
    { name: "rss feed", filled: false },
    { name: "screen rotation alt", filled: true },
    { name: "screen rotation alt", filled: false },
    { name: "signal cellular alt", filled: true },
    { name: "signal cellular alt", filled: false },
    { name: "signal wifi bad", filled: true },
    { name: "signal wifi bad", filled: false },
    { name: "signal_wifi_statusbar_not_connected", filled: true },
    { name: "signal_wifi_statusbar_not_connected", filled: false },
    { name: "usb", filled: true },
    { name: "usb", filled: false },
    { name: "wifi_2_bar", filled: true },
    { name: "wifi_2_bar", filled: false },
    { name: "wifi tethering", filled: true },
    { name: "wifi tethering", filled: false },
    { name: "wifi notification", filled: true },
    { name: "wifi notification", filled: false },
    { name: "wifi calling 2", filled: true },
    { name: "wifi calling 2", filled: false },
    { name: "all inclusive", filled: true },
    { name: "all inclusive", filled: false },
    { name: "backup", filled: true },
    { name: "backup", filled: false },
    { name: "webhook", filled: true },
    { name: "webhook", filled: false },
    { name: "wifi protected setup", filled: true },
    { name: "wifi protected setup", filled: false },
    { name: "bigtop updates", filled: true },
    { name: "bigtop updates", filled: false },
    { name: "cloud", filled: true },
    { name: "cloud", filled: false },
    { name: "cloud done", filled: true },
    { name: "cloud done", filled: false },
    { name: "cloud download", filled: true },
    { name: "cloud download", filled: false },
    { name: "cloud sync", filled: true },
    { name: "cloud sync", filled: false },
    { name: "communities", filled: true },
    { name: "communities", filled: false },
    { name: "google wifi", filled: true },
    { name: "google wifi", filled: false },
    { name: "leak add", filled: true },
    { name: "leak add", filled: false },
    { name: "nest remote comfort sensor", filled: true },
    { name: "nest remote comfort sensor", filled: false },
    { name: "podcasts", filled: true },
    { name: "podcasts", filled: false },
    { name: "public", filled: true },
    { name: "public", filled: false },
    { name: "settings ethernet", filled: true },
    { name: "settings ethernet", filled: false },
    { name: "sensors", filled: true },
    { name: "sensors", filled: false },
    { name: "share", filled: true },
    { name: "share", filled: false },
    { name: "share off", filled: true },
    { name: "share off", filled: false },
    { name: "vpn key", filled: true },
    { name: "vpn key", filled: false },
    { name: "wifi channel", filled: true },
    { name: "wifi channel", filled: false },
    { name: "desktop mac", filled: true },
    { name: "desktop mac", filled: false },
    { name: "devices", filled: true },
    { name: "devices", filled: false },
    { name: "device unknown", filled: true },
    { name: "device unknown", filled: false },
    { name: "device hub", filled: true },
    { name: "device hub", filled: false },
    { name: "earbuds", filled: true },
    { name: "earbuds", filled: false },
    { name: "lda", filled: true },
    { name: "lda", filled: false },
    { name: "merge", filled: true },
    { name: "merge", filled: false },
    { name: "pacemaker", filled: true },
    { name: "pacemaker", filled: false },
    { name: "route", filled: true },
    { name: "route", filled: false },
    { name: "router", filled: true },
    { name: "router", filled: false },
    { name: "save", filled: true },
    { name: "save", filled: false },
    { name: "settings input antenna ", filled: true },
    { name: "settings input antenna ", filled: false },
    { name: "settings input component", filled: true },
    { name: "settings input component", filled: false },
    { name: "settings input hdmi", filled: true },
    { name: "settings input hdmi", filled: false },
    { name: "settings_input_svideo", filled: true },
    { name: "settings_input_svideo", filled: false },
    { name: "smart toy", filled: true },
    { name: "smart toy", filled: false },
    { name: "settings remote", filled: true },
    { name: "settings remote", filled: false },
    { name: "sim card", filled: true },
    { name: "sim card", filled: false },
    { name: "tty", filled: true },
    { name: "tty", filled: false },
    { name: "ventilator", filled: true },
    { name: "ventilator", filled: false },
    { name: "component_exchange", filled: true },
    { name: "component_exchange", filled: false },
    { name: "circles ext", filled: true },
    { name: "circles ext", filled: false },
    { name: "code blocks", filled: true },
    { name: "code blocks", filled: false },
    { name: "polymer", filled: true },
    { name: "polymer", filled: false },
    { name: "cast", filled: true },
    { name: "cast", filled: false },
    { name: "browser updated", filled: true },
    { name: "browser updated", filled: false },
    { name: "login", filled: true },
    { name: "login", filled: false },
    { name: "logout", filled: true },
    { name: "logout", filled: false },
    { name: "toggle on", filled: true },
    { name: "toggle on", filled: false },
    { name: "bolt", filled: true },
    { name: "bolt", filled: false },
    { name: "auto renew", filled: true },
    { name: "auto renew", filled: false },
    { name: "delete forever", filled: true },
    { name: "delete forever", filled: false },
    { name: "outlet", filled: true },
    { name: "outlet", filled: false },
    { name: "heat pump balance", filled: true },
    { name: "heat pump balance", filled: false },
    { name: "forward", filled: true },
    { name: "forward", filled: false },
    { name: "switch access shortcut", filled: true },
    { name: "switch access shortcut", filled: false },
    { name: "rebase", filled: true },
    { name: "rebase", filled: false },
    { name: "rebase edit", filled: true },
    { name: "rebase edit", filled: false },
    { name: "arrow split", filled: true },
    { name: "arrow split", filled: false },
    { name: "linked services", filled: true },
    { name: "linked services", filled: false },
    { name: "polyline", filled: true },
    { name: "polyline", filled: false },
    { name: "refresh", filled: true },
    { name: "refresh", filled: false },
  ],
};
